from __future__ import annotations
from typing import Protocol, List, Optional
from .domain import Order

class OrderRepository(Protocol):
    def get(self, id: int) -> Optional[Order]: ...
    def find_by_customer(self, customer_id: int, limit: int = 100, offset: int = 0) -> List[Order]: ...
    def save(self, order: Order) -> int: ...
    def delete(self, id: int) -> None: ...
